# Generated by Django 5.2 on 2025-04-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("description", models.CharField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("B", "Basic"),
                            ("I", "Intermediary"),
                            ("A", "Advanced"),
                        ],
                        default="B",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("cpf", models.CharField(max_length=11)),
                ("birth_date", models.DateField()),
                ("phone_number", models.CharField(max_length=14)),
            ],
        ),
    ]
