# Generated by Django 5.2 on 2025-04-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
