# Generated by Django 5.2 on 2025-04-29 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0003_alter_student_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
